version: "3.3"

services:
  pcs2019-2:
    build: .
    ports:
      - "3000:3000"
    command: yarn start   
    depends_on: 
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
